deny = [
    "unsafe_code",
    "trivial_casts",
    "clippy::as_underscore",
    "clippy::cast_lossless",
    "clippy::undocumented_unsafe_blocks",
    "clippy::unnecessary_cast",
]

warn = [
    "clippy::alloc_instead_of_core",
    "clippy::allow_attributes_without_reason",
    "clippy::borrow_as_ptr",
    "clippy::cast_possible_truncation",
    "clippy::cast_possible_wrap",
    "clippy::cast_sign_loss",
    "clippy::cloned_instead_of_copied",
    "clippy::dbg_macro",
    "clippy::decimal_literal_representation",
    "clippy::default_trait_access",
    "clippy::enum_glob_use",
    "clippy::equatable_if_let",
    "clippy::explicit_into_iter_loop",
    "clippy::explicit_iter_loop",
    "clippy::filter_map_next",
    "clippy::flat_map_option",
    "clippy::from_iter_instead_of_collect",
    "clippy::get_unwrap",
    "clippy::if_not_else",
    "clippy::if_then_some_else_none",
    "clippy::implicit_clone",
    "clippy::inconsistent_struct_constructor",
    "clippy::items_after_statements",
    "clippy::manual_ok_or",
    "clippy::manual_string_new",
    "clippy::map_unwrap_or",
    "clippy::match_on_vec_items",
    "clippy::match_same_arms",
    "clippy::match_wildcard_for_single_variants",
    "clippy::mismatching_type_param_order",
    "clippy::multiple_crate_versions",
    "clippy::multiple_inherent_impl",
    "clippy::needless_for_each",
    "clippy::option_if_let_else",
    "clippy::option_if_let_else",
    "clippy::print_stdout",
    "clippy::redundant_closure_for_method_calls",
    "clippy::redundant_else",
    "clippy::return_self_not_must_use",
    "clippy::semicolon_if_nothing_returned",
    "clippy::single_match_else",
    "clippy::stable_sort_primitive",
    "clippy::str_to_string",
    "clippy::string_lit_as_bytes",
    "clippy::trait_duplication_in_bounds",
    "clippy::unneeded_field_pattern",
    "clippy::unnested_or_patterns",
    "clippy::unseparated_literal_suffix",
    "clippy::wildcard_enum_match_arm",

    # TODO(rust 1.66):
    # "clippy::uninlined_format_args",

    # TODO: enable closer to 1.0
    # "clippy::print_stderr",
    # "clippy::todo",
    # "clippy::unimplemented",
    # "clippy::use_debug",
]
